# Generated by Django 2.1.8 on 2019-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32)),
                ('type_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
