# Generated by Django 2.1.8 on 2019-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20190909_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_status',
            field=models.IntegerField(default=1),
        ),
    ]
