# Generated by Django 2.1.8 on 2019-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_goodstype_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_pro_time',
            field=models.DateField(),
        ),
    ]
